version: '3'
services:
    db:
        image: mongo
         ports:
            — “27017:27017”
    backend:
        image: node-api
        ports:
            - "8000:8000"
        depends_on:
            - db
    frontend:
        image: cheat-frontend:02
        ports:
            - "3000:80"
        depends_on:
            - backend